### ISSUE TITLE
Bug: application doesn't terminate on receipt of signal interrupt ctrl+c 

### ISSUE THREAD

**Issue by c-nv-s** [abdusco/qme#1]
running as normal unprivileged user on linux.
steps to reproduce:
1. issue an invalid command e.g. ``qme --help``
2. observe that error message received and then application begins idling
3. introduce signal interrupt key sequence ``ctrl+c``
4. application acknowledges interrupt signal received and states shutdown is beginning
5. application hangs indefinitely and doesn't shut down

```
2022/01/26 21:42:13 failed to execute command --help: exec: "--help": executable file not found in $PATH
2022/01/26 21:42:13 idling...
^C2022/01/26 22:04:11 interrupt signal received
2022/01/26 22:04:11 shutting down
```

**Comment by abdusco** [comment]
Thanks for raising this issue @c-nv-s, I'll report back once I replicate the bug.

**Comment by c-nv-s** [comment]
any update on this getting fixed? or is the project now on ice?

**Comment by abdusco** [comment]
@c-nv-s Sorry, I forgot this issue even existed, and no, the project is alive and kicking.

The issue is that there's no argparser used in the app. It considers every argument passed to it as part of the command that will be run.
```
$ qme cmd arg1 arg2
# runs `cmd arg1 arg2`
qme --help
# runs `--help`, which doesn't work
```


I've fixed the Ctrl+C termination issue with https://github.com/abdusco/qme/commit/b7d13f2132ba46a19e2dadbc97762771932df44e, and once I add `--help` support, I'll push a new update
